spring:
  application:
    name: socketingestor
  kafka:
    bootstrap-servers: 'localhost:29092'
    producer:
      acks: "1"
      retries: 1
      properties:
        max.in.flight.requests.per.connection: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


server:
  port: 8080

tradeledger:
  config:
    kafka:
      topics:
        market-data: 'trade.market-data'
